<?php

namespace Database\Seeders;

use App\Models\CompanyService;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Str;

class CompanyServiceSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
       $services = [
            // We Offer (service_sub_category_id = 1)
            [
                'service_category_id' => 1,
                'service_sub_category_id' => 1,
                'is_featured' => '1',
                'name' => 'Door-to-door transport',
                'slug' => Str::slug('Door-to-door transport'),
                'meta_title' => 'Straight from/to your home or office',
                'meta_description' => 'Convenient car transport with pickup and drop-off at your door.',
                'details' => '<p>Safe and reliable door-to-door car shipping tailored to your location.</p>',
                'meta_image' => 'uploads/company/services/service-4.jpg',
                'main_image' => 'uploads/company/services/service6.jpg',
            ],
            [
                'service_category_id' => 1,
                'service_sub_category_id' => 1,
                'is_featured' => '1',
                'name' => 'Open car transport',
                'slug' => Str::slug('Open car transport'),
                'meta_title' => 'Quick and affordable option',
                'meta_description' => 'Most common and cost-effective shipping method.',
                'details' => '<p>Budget-friendly open trailer car transport solution.</p>',
                'meta_image' => 'uploads/company/services/service1.jpg',
                'main_image' => 'uploads/company/services/service-1.jpg',
            ],
            [
                'service_category_id' => 1,
                'service_sub_category_id' => 1,
                'name' => 'Enclosed auto transport',
                'is_featured' => '1',
                'slug' => Str::slug('Enclosed auto transport'),
                'meta_title' => 'Safe and clean option',
                'meta_description' => 'Protection from weather and road debris during transport.',
                'details' => '<p>Enclosed trailer shipping for luxury, antique, or valuable vehicles.</p>',
                'meta_image' => 'uploads/company/services/1745655592_meta_image.jpg',
                'main_image' => 'uploads/company/services/1745655592_main_image.jpg',
            ],
            [
                'service_category_id' => 1,
                'service_sub_category_id' => 1,
                'name' => 'Expedited auto transport',
                'slug' => Str::slug('Expedited auto transport'),
                'meta_title' => 'Guaranteed pick-up date',
                'meta_description' => 'Urgent car transport services with priority pickup.',
                'details' => '<p>Fast-track your car shipment with our expedited services.</p>',
                'meta_image' => 'uploads/company/services/service1.jpg',
                'main_image' => 'uploads/company/services/service1.jpg',
            ],
            [
                'service_category_id' => 1,
                'service_sub_category_id' => 1,
                'name' => 'Hawaii car transport',
                'slug' => Str::slug('Hawaii car transport'),
                'meta_title' => 'Ship from/to Hawaii',
                'meta_description' => 'Specialized car shipping services to and from Hawaii.',
                'details' => '<p>Seamless car shipping between mainland U.S. and Hawaii.</p>',
                'meta_image' => 'uploads/company/services/service1.jpg',
                'main_image' => 'uploads/company/services/service1.jpg',
            ],
            [
                'service_category_id' => 1,
                'service_sub_category_id' => 1,
                'name' => 'Puerto Rico car transport',
                'slug' => Str::slug('Puerto Rico car transport'),
                'meta_title' => 'Ship from/to Puerto Rico',
                'meta_description' => 'Affordable car transport from and to Puerto Rico.',
                'details' => '<p>Licensed and insured transport to/from Puerto Rico.</p>',
                'meta_image' => 'uploads/company/services/service1.jpg',
                'main_image' => 'uploads/company/services/service1.jpg',
            ],
            [
                'service_category_id' => 1,
                'service_sub_category_id' => 1,
                'name' => 'Guam car transport',
                'slug' => Str::slug('Guam car transport'),
                'meta_title' => 'Ship from/to Guam',
                'meta_description' => 'Dependable car shipping services for Guam routes.',
                'details' => '<p>Transport your car safely to or from Guam with ease.</p>',
                'meta_image' => 'uploads/company/services/service1.jpg',
                'main_image' => 'uploads/company/services/service1.jpg',
            ],

            // We Serve (service_sub_category_id = 2)
            [
                'service_category_id' => 1,
                'service_sub_category_id' => 2,
                'is_featured' => '1',
                'name' => 'Car relocation services',
                'slug' => Str::slug('Car relocation services'),
                'meta_title' => 'Private or corporate moves',
                'meta_description' => 'Vehicle relocation for moves, jobs, or lifestyle changes.',
                'details' => '<p>Relocate your vehicle stress-free to any destination.</p>',
                'meta_image' => 'uploads/company/services/service4.jpg',
                'main_image' => 'uploads/company/services/service-4.jpg',
            ],
            [
                'service_category_id' => 1,
                'service_sub_category_id' => 2,
                'name' => 'Online car buyers',
                'slug' => Str::slug('Online car buyers'),
                'meta_title' => 'Bought and shipped online',
                'meta_description' => 'Ship cars bought online directly to your location.',
                'details' => '<p>Buy a car online and let us handle the delivery.</p>',
                'meta_image' => 'uploads/company/services/service1.jpg',
                'main_image' => 'uploads/company/services/service1.jpg',
            ],
            [
                'service_category_id' => 1,
                'service_sub_category_id' => 2,
                'name' => 'Motorcycle shipping',
                'is_featured' => '1',
                'slug' => Str::slug('Motorcycle shipping'),
                'meta_title' => 'Scenic drives and road adventures',
                'meta_description' => 'Safe transport for your motorcycle across states.',
                'details' => '<p>Reliable motorcycle transport with secure handling.</p>',
                'meta_image' => 'uploads/company/services/1745654331_main_image.jpg',
                'main_image' => 'uuploads/company/services/1745654331_meta_image.jpg',
            ],
            [
                'service_category_id' => 1,
                'service_sub_category_id' => 2,
                'name' => 'Student car shipping',
                'slug' => Str::slug('Student car shipping'),
                'meta_title' => 'Move from/to the college campus',
                'meta_description' => 'Ship cars for college students to and from campus.',
                'details' => '<p>Helping students and families move cars across campuses nationwide.</p>',
                'meta_image' => 'uploads/company/services/service1.jpg',
                'main_image' => 'uploads/company/services/service1.jpg',
            ],
            [
                'service_category_id' => 1,
                'service_sub_category_id' => 2,
                'name' => 'Ship a car to another state',
                'slug' => Str::slug('Ship a car to another state'),
                'meta_title' => 'Ship from/to any state',
                'meta_description' => 'Car transport across U.S. states, quick and secure.',
                'details' => '<p>Transport your car across state lines safely and affordably.</p>',
                'meta_image' => 'uploads/company/services/service1.jpg',
                'main_image' => 'uploads/company/services/service1.jpg',
            ],
            [
                'service_category_id' => 1,
                'service_sub_category_id' => 2,
                'name' => 'Snowbird car shipping',
                'slug' => Str::slug('Snowbird car shipping'),
                'meta_title' => 'Move to the endless summer',
                'meta_description' => 'Seasonal car shipping for snowbirds heading south.',
                'details' => '<p>Enjoy the sunshine while we handle your winter car relocation.</p>',
                'meta_image' => 'uploads/company/services/service1.jpg',
                'main_image' => 'uploads/company/services/service1.jpg',
            ],

            [
                'service_category_id' => 1,
                'service_sub_category_id' => 2,
                'is_featured' => '1',
                'name' => 'Luxury/exotic car shipping',
                'slug' => Str::slug('Luxury/exotic car shipping'),
                'meta_title' => 'High-end luxury vehicles',
                'meta_description' => 'Transport your luxury or exotic car with white-glove care and safety.',
                'details' => '<p>We specialize in enclosed and high-security shipping for your luxury, exotic, or collector vehicles.</p>',
                'meta_image' => 'uploads/company/services/1745655048_main_image.jpg',
                'main_image' => 'uploads/company/services/1745655048_main_image.jpg',
            ],
            [
                'service_category_id' => 1,
                'service_sub_category_id' => 2,
                'name' => 'Car resellers',
                'slug' => Str::slug('Car resellers'),
                'meta_title' => 'Delivered to your client',
                'meta_description' => 'Streamlined vehicle delivery services for dealerships and car resellers.',
                'details' => '<p>Get cars delivered to your buyers fast and professionally with our tailored reseller solutions.</p>',
                'meta_image' => 'uploads/company/services/service1.jpg',
                'main_image' => 'uploads/company/services/service1.jpg',
            ],
            [
                'service_category_id' => 1,
                'service_sub_category_id' => 2,
                'name' => 'Military car shipping',
                'slug' => Str::slug('Military car shipping'),
                'meta_title' => 'The home of the brave',
                'meta_description' => 'Vehicle relocation support for military personnel and their families.',
                'details' => '<p>We offer discounted, dependable car shipping services for active duty members of the armed forces.</p>',
                'meta_image' => 'uploads/company/services/service1.jpg',
                'main_image' => 'uploads/company/services/service1.jpg',
            ],
            [
                'service_category_id' => 1,
                'service_sub_category_id' => 2,
                'name' => 'International car shipping',
                'slug' => Str::slug('International car shipping'),
                'meta_title' => 'Move overseas',
                'meta_description' => 'Global vehicle shipping solutions by land and sea.',
                'details' => '<p>We help you ship your car internationally with complete documentation and port-to-port service.</p>',
                'meta_image' => 'uploads/company/services/service1.jpg',
                'main_image' => 'uploads/company/services/service1.jpg',
            ],
            [
                'service_category_id' => 1,
                'service_sub_category_id' => 2,
                'name' => 'Truck shipping services',
                'slug' => Str::slug('Truck shipping services'),
                'meta_title' => 'Pickups, oversized, or custom',
                'meta_description' => 'Reliable transport for pickups, lifted trucks, and oversized vehicles.',
                'details' => '<p>We transport all types of trucks — standard, heavy-duty, or customized builds — with ease and care.</p>',
                'meta_image' => 'uploads/company/services/service1.jpg',
                'main_image' => 'uploads/company/services/service1.jpg',
            ],

            [
                'service_category_id' => 2,
                'service_sub_category_id' => 3,
                'name' => 'Auto dealerships & groups',
                'slug' => Str::slug('Auto dealerships & groups'),
                'meta_title' => 'Streamlined customer service',
                'meta_description' => 'Streamlined customer service for auto dealerships and groups.',
                'details' => '<p>We provide reliable vehicle transport solutions for dealerships and dealer groups to enhance customer satisfaction.</p>',
                'meta_image' => 'uploads/company/services/service1.jpg',
                'main_image' => 'uploads/company/services/service1.jpg',
            ],
            [
                'service_category_id' => 2,
                'service_sub_category_id' => 3,
                'name' => 'Auto auctions',
                'slug' => Str::slug('Auto auctions'),
                'meta_title' => 'Transport speed and efficiency',
                'meta_description' => 'Fast and efficient transport solutions for auto auctions.',
                'details' => '<p>Ensure quick and smooth vehicle moves for auction events with our speed-optimized logistics.</p>',
                'meta_image' => 'uploads/company/services/service1.jpg',
                'main_image' => 'uploads/company/services/service1.jpg',
            ],
            [
                'service_category_id' => 2,
                'service_sub_category_id' => 3,
                'name' => 'Fleet management',
                'slug' => Str::slug('Fleet management'),
                'meta_title' => 'Inventory rotation expertise',
                'meta_description' => 'Efficient fleet vehicle movement and rotation.',
                'details' => '<p>Rotate, relocate, and manage your fleet inventory with precision and control.</p>',
                'meta_image' => 'uploads/company/services/service1.jpg',
                'main_image' => 'uploads/company/services/service1.jpg',
            ],
            [
                'service_category_id' => 2,
                'service_sub_category_id' => 3,
                'name' => 'Financial institutions',
                'slug' => Str::slug('Financial institutions'),
                'meta_title' => 'Credit and repossessions',
                'meta_description' => 'Secure transport for financial services including repossessions.',
                'details' => '<p>Specialized vehicle logistics for lenders and repossession management.</p>',
                'meta_image' => 'uploads/company/services/service1.jpg',
                'main_image' => 'uploads/company/services/service1.jpg',
            ],
            [
                'service_category_id' => 2,
                'service_sub_category_id' => 3,
                'name' => 'OEM auto transport',
                'slug' => Str::slug('OEM auto transport'),
                'meta_title' => 'National service coverage',
                'meta_description' => 'Nationwide OEM transport with efficiency and care.',
                'details' => '<p>From factory to showroom, we deliver OEM vehicles safely across the country.</p>',
                'meta_image' => 'uploads/company/services/service1.jpg',
                'main_image' => 'uploads/company/services/service1.jpg',
            ],
            [
                'service_category_id' => 2,
                'service_sub_category_id' => 3,
                'name' => 'Rental car companies',
                'slug' => Str::slug('Rental car companies'),
                'meta_title' => 'Scaled inventory management',
                'meta_description' => 'Vehicle logistics for rental car companies.',
                'details' => '<p>Manage, relocate, and scale your rental fleet effectively with our transport solutions.</p>',
                'meta_image' => 'uploads/company/services/service1.jpg',
                'main_image' => 'uploads/company/services/service1.jpg',
            ],
            [
                'service_category_id' => 2,
                'service_sub_category_id' => 4,
                'name' => 'Logistics',
                'slug' => Str::slug('Logistics'),
                'meta_title' => 'Transportation management',
                'meta_description' => 'Comprehensive logistics and transportation services.',
                'details' => '<p>Streamlined end-to-end vehicle transportation management for your business operations.</p>',
                'meta_image' => 'uploads/company/services/service1.jpg',
                'main_image' => 'uploads/company/services/service1.jpg',
            ],
            [
                'service_category_id' => 2,
                'service_sub_category_id' => 4,
                'name' => 'Montway automation portal',
                'slug' => Str::slug('Montway automation portal'),
                'meta_title' => 'Centralized operations platform',
                'meta_description' => 'Automated car transport platform for dealers and businesses.',
                'details' => '<p>Manage and streamline your vehicle moves with our powerful automation platform.</p>',
                'meta_image' => 'uploads/company/services/service1.jpg',
                'main_image' => 'uploads/company/services/service1.jpg',
            ],
            [
                'service_category_id' => 2,
                'service_sub_category_id' => 4,
                'name' => 'Home delivery for dealerships',
                'slug' => Str::slug('Home delivery for dealerships'),
                'meta_title' => 'Driveaway service',
                'meta_description' => 'Door-to-door vehicle delivery service for car dealerships.',
                'details' => '<p>Offer your customers convenience with direct home delivery of vehicles.</p>',
                'meta_image' => 'uploads/company/services/service1.jpg',
                'main_image' => 'uploads/company/services/service1.jpg',
            ],
            [
                'service_category_id' => 2,
                'service_sub_category_id' => 5,
                'name' => 'Corporate relocations',
                'slug' => Str::slug('Corporate relocations'),
                'meta_title' => 'Program management',
                'meta_description' => 'Vehicle relocation services for businesses and employees.',
                'details' => '<p>Relocate employee or company vehicles seamlessly as part of your corporate move.</p>',
                'meta_image' => 'uploads/company/services/service1.jpg',
                'main_image' => 'uploads/company/services/service1.jpg',
            ],
        ];

        foreach ($services as $service) {
            CompanyService::create($service);
        }
    }
}
